-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trabalhopoo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalhopoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalhopoo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `trabalhopoo` ;

-- -----------------------------------------------------
-- Table `trabalhopoo`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhopoo`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `periodo` INT(11) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhopoo`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhopoo`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `categoria` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Categoria_idx` (`categoria` ASC),
  CONSTRAINT `fk_Usuario_Categoria`
    FOREIGN KEY (`categoria`)
    REFERENCES `trabalhopoo`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhopoo`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhopoo`.`Livro` (
  `idLivro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `isbn` VARCHAR(15) NULL,
  `assunto` VARCHAR(45) NULL,
  `autores` VARCHAR(150) NULL,
  `exemplar` INT(11) NULL,
  PRIMARY KEY (`idLivro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhopoo`.`Emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhopoo`.`Emprestimo` (
  `idEmprestimo` INT NOT NULL AUTO_INCREMENT,
  `emprestimo` DATE NOT NULL,
  `devolucao` DATE NULL,
  `usuario` INT NOT NULL,
  `livro` INT NOT NULL,
  PRIMARY KEY (`idEmprestimo`),
  INDEX `fk_Emprestimo_Usuario1_idx` (`usuario` ASC),
  INDEX `fk_Emprestimo_Livro1_idx` (`livro` ASC),
  CONSTRAINT `fk_Emprestimo_Usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `trabalhopoo`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emprestimo_Livro1`
    FOREIGN KEY (`livro`)
    REFERENCES `trabalhopoo`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
